- docs/almanac-registration.md
- docs/remote-agents.md
This is for the issues found in the documentation. @jrriehl @Alejandro-Morales
> Edits to documentation

- examples/13-send-tokens/main.py
- src/uagents/agent.py
- src/uagents/network.py
I think this simplified tx flow is all we need at the moment. I applied this to the registration tx and also added a send tokens example.
> feat: simplify cosmpy txs and add example

- examples/09-booking-protocol-demo/query.py
- examples/09-booking-protocol-demo/restaurant.py
- src/uagents/context.py
- src/uagents/contrib/protocols/protocol_query.py
Adds a built-in protocol for responding to protocol queries, that is, requests to retrieve the manifest of a particular protocol, or if none is specified, all protocols included in the agent are included in the response.
> feat: add protocol query in contrib module

- python/docs/api/uagents/agent.md
- python/docs/api/uagents/asgi.md
- python/docs/api/uagents/config.md
- python/docs/api/uagents/context.md
- python/docs/api/uagents/crypto/__init__.md
- python/docs/api/uagents/dispatch.md
- python/docs/api/uagents/envelope.md
- python/docs/api/uagents/mailbox.md
- python/docs/api/uagents/models.md
- python/docs/api/uagents/network.md
- python/docs/api/uagents/protocol.md
- python/mkdocs.yml
- python/scripts/generate_api_docs.py
- python/src/uagents/agent.py
- python/src/uagents/asgi.py
- python/src/uagents/config.py
- python/src/uagents/context.py
- python/src/uagents/crypto/__init__.py
- python/src/uagents/dispatch.py
- python/src/uagents/envelope.py
- python/src/uagents/mailbox.py
- python/src/uagents/models.py
- python/src/uagents/network.py
- python/src/uagents/protocol.py
Adds some missing docstrings and files, and updates some others.
> docs: add missing docstrings and other updates

- python/src/uagents/agent.py
Send `ErrorMessage` back to sender when message fails validation.
> feat: report validation errors back to sender

- python/scripts/do_release.py
Release script was failing because of this.
> fix: remove verify-tag flag from create release cmd

- python/src/uagents/resolver.py
> fix: parse user addresses

- .github/workflows/ci-tests.yml
- python/README.md
- python/poetry.lock
- python/pyproject.toml
Also ran `poetry lock` to update all dependencies.
> feat: support Python 3.12

- integrations/ai-web-scrapper/README.md
- integrations/ai-web-scrapper/agent.py
- integrations/ai-web-scrapper/project.json
- integrations/ai-web-scrapper/requirements.txt
- integrations/ai-web-scrapper/server.py
- integrations/ai-web-scrapper/utils.py
This project implements a web scraper and summarizer API integrated with a question answering system. It utilizes Flask for creating the API endpoints and integrates with langchain for web scraping, summarization, and for question answering tasks it utilizes the Hugging Face model.
[Screencast from 15-03-24 09_32_47 PM IST.webm](https://github.com/fetchai/uAgents/assets/140384949/048edb28-8869-4e76-8499-9e593e3df6db)
> feat: add ai web scraper

- integrations/travel-agent/README.md
- integrations/travel-agent/pyproject.toml
- integrations/travel-agent/src/agents/h_agent.py
- integrations/travel-agent/src/agents/protocols/destination.py
- integrations/travel-agent/src/agents/protocols/flight.py
- integrations/travel-agent/src/agents/protocols/hotel.py
- integrations/travel-agent/src/agents/tempCodeRunnerFile.py
- integrations/travel-agent/src/agents/travel.py
- integrations/travel-agent/src/agents/user_agent.py
Hackathon- AGENT-X
Team Members :-
Shubham Sharma 
Shailesh Kumar
Shah Diya Manojkumar
Yogendra Pandey
Sumeet Gaikwad
> Agentx- TravelAgent-TombaAPI

- integrations/SmartHire/README.md
- integrations/SmartHire/agents/gemini_agent.py
- integrations/SmartHire/agents/user.py
- integrations/SmartHire/main.py
- integrations/SmartHire/project.json
- integrations/SmartHire/requirements.txt
Welcome to the AI Interviewer Platform! Our innovative platform leverages artificial intelligence to conduct interviews, providing a seamless and efficient experience for both interviewers and interviewees.
The AI Interviewer Platform revolutionizes the interview process by integrating cutting-edge AI technology as the interviewer. Gone are the days of scheduling conflicts, biased judgments, and human limitations in assessing candidates. With our platform, interviews can be conducted anytime, anywhere, with consistent and objective evaluation criteria.
Our platform employs state-of-the-art natural language processing algorithms to formulate insightful questions and analyze responses in real-time. Interviewees interact with the AI interviewer through a user-friendly interface, answering …
> PICT - Mitochondria

- .github/workflows/ci-tests.yml
- python/examples/17-stateful-communication/agent1.py
- python/examples/17-stateful-communication/agent2.py
- python/examples/17-stateful-communication/agent3.py
- python/examples/17-stateful-communication/agent4.py
- python/examples/17-stateful-communication/dialogues/chitchat.py
- python/examples/17-stateful-communication/dialogues/hardcoded_chitchat.py
- python/examples/17-stateful-communication/dialogues/simple_chitchat.py
- python/src/uagents/experimental/dialogues/__init__.py
- python/src/uagents/storage/__init__.py
Introduce the `StorageAPI` as a generalised interface for agent based storage solutions.
This should also make it (slightly) easier to create ORM or DB like storage adapters for agents.
Dialogues now use that interface which in turn makes the instantiation more user-friendly.
> feat(core): generalise dialogue storage solution

- python/src/uagents/experimental/dialogues/__init__.py
provide an interface for the cleanup task interval (which acts as a multiplier for the timeout that is set per Dialogue instance), i.e. it affects how long the messages are seen as valid.
Setting it to 0 will disable the cleanup task altogether if you want to handle that separately.
> refactor(core): dialogue cleanup task handling

- python/docs/api/uagents/agent.md
- python/docs/api/uagents/asgi.md
- python/docs/api/uagents/communication.md
- python/docs/api/uagents/config.md
- python/docs/api/uagents/context.md
- python/docs/api/uagents/dispatch.md
- python/docs/api/uagents/envelope.md
- python/docs/api/uagents/experimental/__init__.md
- python/docs/api/uagents/experimental/dialogues/__init__.md
- python/docs/api/uagents/mailbox.md
- python/docs/api/uagents/models.md
- python/docs/api/uagents/network.md
- python/docs/api/uagents/query.md
- python/docs/api/uagents/resolver.md
- python/docs/api/uagents/setup.md
- python/docs/api/uagents/storage/__init__.md
- python/docs/api/uagents/utils.md
- python/docs/api/uagents/wallet_messaging.md
- python/examples/01-first-agent/main.py
- python/examples/02-interval-task/main.py
- python/examples/03-multiple-agents/main.py
- python/examples/06-send-tokens/main.py
- python/examples/09-booking-protocol-demo/query.py
- python/examples/09-booking-protocol-demo/restaurant.py
- python/examples/13-agent-name-service/agent1.py
- python/examples/14-broadcast/main.py
- python/examples/17-stateful-communication/agent5.py
- python/examples/17-stateful-communication/dialogues/agentverse_chitchat.py
edit: updated API docs as well
> chore(example): fix agent examples for new context

- .github/ISSUE_TEMPLATE/feature-request.yml
Updates feature request template
_What types of changes does the pull request introduce? Put an `x` in the boxes that apply:_
> chore(core): Update feature-request.yml

- README.md
Bugfix in readme
Seems the context doesn't have `name` attribute
```
ERROR:    [alice]: Exception in interval handler: 'InternalContext' object has no attribute 'name'
Traceback (most recent call last):
File "/Users/tomasz.strzeszkowski/.pyenv/versions/3.11.2/lib/python3.11/site-packages/uagents/agent.py", line 73, in _run_interval
await func(ctx)
File "<stdin>", line 3, in say_hello
AttributeError: 'InternalContext' object has no attribute 'name'
```
https://github.com/fetchai/uAgents/issues/395
_What types of changes does the pull request introduce? Put an `x` in the boxes that apply:_
_(If this is a relatively large or complex change, kick off a discussion by explaining why you chose the solution you did, what alternatives you considered, etc...)._
> docs(core): example in readme

- .github/pull-request-template.md
Update PR template (this one!)
_What types of changes does the pull request introduce? Put an `x` in the boxes that apply:_
> chore(core): Update Templates

- .github/PULL_REQUEST_TEMPLATE/release.md
Describe the changes provided by this Pull Request here.
If applicable, add links to any issues resolved by this Pull Request.
_What types of changes does the pull request introduce? Put an `x` in the boxes that apply:_
_(If this is a relatively large or complex change, kick off a discussion by explaining why you chose the solution you did, what alternatives you considered, etc...)._
> chore(core): Update release.md

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
> fix(core): Update bug-report.yml

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- CONTRIBUTING.md
- SECURITY.md
minor updates top the health files
> chore(core): repo health files

- README.md
- python/docs/api/uagents/agent.md
- python/docs/api/uagents/communication.md
- python/docs/api/uagents/config.md
- python/docs/api/uagents/context.md
- python/docs/api/uagents/envelope.md
- python/docs/api/uagents/experimental/dialogues/__init__.md
- python/docs/api/uagents/network.md
- python/docs/api/uagents/query.md
- python/docs/api/uagents/resolver.md
- python/docs/api/uagents/storage/__init__.md
- python/docs/api/uagents/utils.md
- python/src/uagents/agent.py
- python/src/uagents/asgi.py
- python/src/uagents/communication.py
- python/src/uagents/config.py
- python/src/uagents/context.py
- python/src/uagents/envelope.py
- python/src/uagents/experimental/dialogues/__init__.py
- python/src/uagents/network.py
- python/src/uagents/query.py
- python/src/uagents/resolver.py
- python/src/uagents/storage/__init__.py
- python/src/uagents/utils.py
This PR addresses a lot of typing inconsistencies and aims to fix Pylance and Pyright warnings.
It also fixes fetching the correct protocol on creation of the ExternalContext within `_process_message_queue()` and the odd typo and missing doctoring.
> chore(core): fix typing issues

- python/pyproject.toml
> chore(core): bump version to 0.12.3

- python/scripts/do_release.py
> fix(core): release script README path

- integrations/fetch-ai-engine/poetry.lock
- integrations/fetch-ai-engine/pyproject.toml
- [ x] Something else (e.g., tests, scripts, example, deployment, infrastructure).
> chore(integration): Update dependencies for ai-engine: uagents to latest, pydantic to 2.7

- README.md
Updated readme code blocks to include syntax highlighting
N/A
N/A
> docs(core): update readme to include syntax highlighting

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/pull_request_template.md
Minor changes tot the repo health files
> fix(core): minor fixes to the repo health files

- python/examples/08-local-network-interaction/agent1.py
- python/src/uagents/resolver.py
Added a new `AlmanacApiResolver` and updated the GlobalResolver to use it before the existing AlmanacResolver.
> feat(core): added alamanc API resolver

- python/pyproject.toml
> chore(core): bump version to 0.12.4

- python/pyproject.toml
> chore(core): bump version to 0.13.0

- integrations/fetch-ai-engine/poetry.lock
- integrations/fetch-ai-engine/pyproject.toml
> feat(integration): Update fetch-ai-engine uagents dependency

- python/src/uagents/communication.py
- python/tests/test_agent_registration.py
- python/tests/test_context.py
Replace the `asyncio.sleep(0)` hot loop with a polling async queue.
Fixes #422 
Closes #443 
> fix(core): replace async yield hot loop with queue

- integrations/fetch-ai-engine/poetry.lock
- integrations/fetch-ai-engine/pyproject.toml
- integrations/fetch-ai-engine/src/ai_engine/messages.py
- integrations/fetch-ai-engine/src/ai_engine/types.py
> chore(integration): AI-Engine package update to latest uagents

- .github/pull_request_template.md
Minor fix to a link in the PR template file
> fix(core): Update pull_request_template.md

- python/pyproject.toml
Patch release to fix minor bug in Almanac API resolution.
> chore(core): bump version to 0.15.1

- python/pyproject.toml
> chore(core): bump version to 0.15.2 for release

- .github/CODEOWNERS
> chore(core): Update CODEOWNERS

- integrations/user-public-repositories/README.md
- integrations/user-public-repositories/get_public_repositories.py
- integrations/user-public-repositories/project.json
- integrations/user-public-repositories/pyproject.toml
Add a new integration that queries the public repositories of a specified GitHub account.
N/A
Added a new integration to query all public repositories of a GitHub user. The account username is provided by the user, and the repositories are listed in order of most-recently contributed to least-recently contributed to. This agent is hosted on the Agentverse and has a Agent Function publicly available to use on DeltaV.
> feat(integration): User GitHub Repositories Integration

- python/src/uagents/registration.py
This PR introduces AgentGeoLocation and adds it to the pydantic model of AgentRegistrationAttestation.
> feat(core): add agent location to AgentRegistrationAttestation

- python/pyproject.toml
> chore(core): bump version to 0.16.0 for release

- python/pyproject.toml
> chore(core): bump version to v0.16.1

- python/pyproject.toml
> chore(core): bump version to 0.16.2 for release

- python/src/uagents/agent.py
Add agent address as query parameter in local agent inspector link and change log level to info.
> chore(core): add agent address as query param in inspector link

- python/pyproject.toml
> chore(core): bump version to 0.17.0

- python/pyproject.toml
> chore(core): bump version to 0.17.1

- python/src/uagents/mailbox.py
Fix auth header for details update.
> fix(core): auth header on update

- python/pyproject.toml
> chore(core): bump version to 0.18.0 for release

- python/pyproject.toml
> chore(core): update version to.0.18.1 for release

- python/src/uagents/setup.py
Update get_ledger function to use new network argument.
> fix(core): get ledger in setup.py

- python/src/uagents/agent.py
- python/src/uagents/context.py
- python/src/uagents/experimental/mobility/__init__.py
- python/src/uagents/experimental/mobility/protocols/base_protocol.py
- python/src/uagents/experimental/search/__init__.py
- python/src/uagents/registration.py
- python/src/uagents/types.py
Add basic mobility agent codebase and protocol.
The agent class will enable automatic interactions between mobility related agents.
> feat(experimental): add mobility agent integration

- python/uagents-core/pyproject.toml
UAgents-Core version bump for release
> chore(core): bump version of uagents-core to 0.1.1

- python/uagents-core/uagents_core/utils/communication.py
> fix(core): uagents_core - fix agent url extraction

- python/uagents-core/pyproject.toml
> chore(core): bump version of uagents-core to 0.1.2

- python/scripts/README.md
- python/scripts/clean_docs.py
- python/scripts/src_links_docs.py
> docs(core): scripts to update and clean docs

- python/src/uagents/protocol.py
Reply model digests were getting sorted randomly, meaning that digests change randomly whenever multiple replies are included in the set.
> fix(core): sort reply digests in manifest

- python/pyproject.toml
> chore(core): bump version to 0.20.1 for release

- python/uagents-core/pyproject.toml
> chore(core): bump version of uagents-core to 0.1.3

- python/poetry.lock
- python/pyproject.toml
Update to fetchai-babble version with more permissive pydantic version constraints.
> chore(core): update fetchai-babble

- python/pyproject.toml
> chore(core): bump version to 0.21.0 for release

- python/uagents-ai-engine/pyproject.toml
Update version to 0.9.0 for uagents-ai-engine release.
> chore(integration): bump versions for uagents-ai-engine release

- python/docs/api/uagents/context.md
- python/uagents-core/uagents_core/contrib/protocols/chat/__init__.py
- python/uagents-core/uagents_core/contrib/protocols/subscriptions/__init__.py
- python/uagents-core/uagents_core/envelope.py
- python/uagents-core/uagents_core/protocol.py
Add the agent subscription protocol spec to uagents_core to allow agents to accept subscribers.
Also fix minor typos.
> feat(core): add agent subscription protocol spec

- python/uagents-core/pyproject.toml
> chore(core): bump version to 0.2.0 for release

- python/scripts/do_release.py
Update release script for new `pyproject.toml` format.
> fix(core): update release script

- python/poetry.lock
- python/pyproject.toml
Update uagents-core and release.
> chore(core): update uagents-core dependency and release

- python/uagents-core/pyproject.toml
Release `uagents-core` v0.2.1.
> chore(core): bump version to 0.2.1 for release

- python/poetry.lock
- python/pyproject.toml
> chore(core): bump version to 0.22.1 for release

- python/uagents-core/uagents_core/utils/messages.py
> fix(core): uagent-core send message util bug

- python/poetry.lock
- python/pyproject.toml
- python/uagents-ai-engine/examples/simple_agent.py
- python/uagents-ai-engine/src/ai_engine/__init__.py
- python/uagents-ai-engine/src/ai_engine/chitchat.py
- python/uagents-ai-engine/src/ai_engine/dialogue.py
- python/uagents-ai-engine/src/ai_engine/messages.py
- python/uagents-ai-engine/src/ai_engine/types.py
- fix import on ai-engine due to the new uagents_core structure
- formatting
> fix(integration): ai-engine uagents.models import

- python/uagents-core/uagents_core/utils/registration.py
> feat(core): metadata support in register_in_almanac method

- python/uagents-core/uagents_core/utils/registration.py
Add response text containing error details to logs on request failure.
> feat(core): add response text to error logs

- python/uagents-core/pyproject.toml
> chore(core): bump uagents-core version to 0.2.3 for release

- python/poetry.lock
- python/pyproject.toml
> chore(core): bump version to 0.22.2 for release

- python/pyproject.toml
Release v0.22.3 (needed for new Almanac contract deployment)
> chore(core): bump version to 0.22.3 for release

- python/uagents-adapter/README.md
Initial uagents adapter release.
> chore(integration): initial uagents adapter release

- python/uagents-adapter/pyproject.toml
Initial release of uagents-adapter.
> chore(integration): initial adapter release

- python/src/uagents/experimental/dialogues/__init__.py
Fixes the unpacking of outbound messages from the provided context.
closes: #689
Please note that although this fix makes dialogues work again it is not meant to be a refactor to be compliant with the new protocol specification.
> fix(core): dialogues outbound messages validation

- python/uagents-adapter/README.md
- python/uagents-adapter/pyproject.toml
> chore(integration): updating adapters registration class

- python/uagents-core/uagents_core/contrib/protocols/chat/__init__.py
- python/uagents-core/uagents_core/storage.py
> feat(core): enable ExternalStorage to create assets using token

- python/uagents-core/pyproject.toml
Release core@0.3.0. Adds support for storage API.
> chore(core): bump version to v0.3.0 for release

- python/poetry.lock
- python/pyproject.toml
Release v0.22.4
Includes minor bug fixes and updates to uagents-core and cosmpy.
> chore(core): bump version to 0.22.4 for release

- python/uagents-adapter/README.md
- python/uagents-adapter/pyproject.toml
- python/uagents-adapter/src/uagents_adapter/__init__.py
- python/uagents-adapter/src/uagents_adapter/mcp/README.md
- python/uagents-adapter/src/uagents_adapter/mcp/__init__.py
- python/uagents-adapter/src/uagents_adapter/mcp/adapter.py
- python/uagents-adapter/src/uagents_adapter/mcp/protocol.py
adding MCP Server Adapter to enable MCP Servers to be registered on Agentverse with Chat Protocol and discoverable by ASI:One
- [x ] New feature added (non-breaking change that adds functionality).
- [x ] I have read the [CONTRIBUTING](https://github.com/fetchai/uAgents/blob/main/CONTRIBUTING.md) guide
- [ x] Checks and tests pass locally
> feat(integration): adding MCP Server Adapter

- python/uagents-adapter/pyproject.toml
bump version uagents-adapter to 0.3.0
- [x ] New feature added (non-breaking change that adds functionality).
- [ x] I have read the [CONTRIBUTING](https://github.com/fetchai/uAgents/blob/main/CONTRIBUTING.md) guide
- [ x] Checks and tests pass locally
> chore(core): bump version uagents-adapter to 0.3.0

- python/uagents-core/uagents_core/storage.py
> feat(core): fix double encoding

- python/uagents-core/pyproject.toml
Release core@0.3.1: small fix to storage encoding.
> chore(core): bump version to 0.3.1 for release

- python/uagents-core/uagents_core/storage.py
> fix(core): correct storage upload typo

- python/docs/api/uagents/network.md
- python/docs/api/uagents/registration.md
- python/poetry.lock
- python/pyproject.toml
- python/src/uagents/network.py
- python/src/uagents/registration.py
This fix is somewhat urgent because our loose constraint on CosmPy means that the latest update introduced a breaking change to ledger transactions, when `gas_limit` was replaced with a `TxFee`.
> fix(core): update to use latest cosmpy tx fees

- python/poetry.lock
- python/pyproject.toml
> chore(core): bump version to 0.22.5 for release

- python/uagents-core/pyproject.toml
Release v0.3.2 (agent status update utility, metadata update, and minor storage fix)
> chore(core): bump version to 0.3.2 for release

- python/uagents-adapter/src/uagents_adapter/langchain/tools.py
**Enhanced LangChain-uAgents Adapter with Comprehensive Async Support**
This PR significantly enhances the LangChain-uAgents adapter to provide full support for modern async patterns including arun(), ainvoke(), and astream() methods, while maintaining complete backward compatibility with existing sync implementations.
**Key Enhancements:**
1. Async Function Detection: Added inspect.iscoroutinefunction() to automatically detect and properly handle async agent functions
2. Priority-Based Method Resolution: Implemented intelligent method selection with the following priority order:
- Async functions → arun() → ainvoke() → run() → invoke() → direct call
3. Enhanced Message Handlers: Updated all three message handlers (handle_query, chat message handler, structured output handler) with async …
> feat(integration): Adding async support to langchain adapter

- python/uagents-core/pyproject.toml
Release core@0.3.4 (subscription util)
> chore(core): bump version to 0.3.4 for release

- python/uagents-adapter/pyproject.toml
> chore(core): bump version uagents-adapter to 0.4.1

- python/uagents-adapter/README.md
- python/uagents-adapter/pyproject.toml
- python/uagents-adapter/src/uagents_adapter/__init__.py
- python/uagents-adapter/src/uagents_adapter/a2a_inbound/README.md
- python/uagents-adapter/src/uagents_adapter/a2a_inbound/__init__.py
- python/uagents-adapter/src/uagents_adapter/a2a_inbound/adapter.py
- python/uagents-adapter/src/uagents_adapter/a2a_inbound/agentverse_executor.py
- python/uagents-adapter/src/uagents_adapter/a2a_inbound/cli.py
> feat(integration): adding a2a inbound adapter

- python/uagents-adapter/pyproject.toml
bump version uagents-adapter to 0.5.0
> chore(core): bump version uagents-adapter to 0.5.0

- python/uagents-core/pyproject.toml
> chore(core): bump version to 0.3.5 for release

- python/poetry.lock
- python/pyproject.toml
> chore(uagents): bump version to 0.22.6 for release

- python/uagents-core/uagents_core/types.py
These extra fields help to automate the agent connection workflow.
> chore(core): add agent type and port to agent info model

- python/uagents-core/pyproject.toml
> chore(core): bump version to 0.3.7 for release

- python/docs/api/uagents/agent.md
- python/poetry.lock
- python/pyproject.toml
- python/src/uagents/agent.py
- python/src/uagents/registration.py
- python/tests/test_flakey_network_registration.py
Updates needed to support new agent info model with agent type and port fields.
> chore(uagents): update to use new agent info model

- python/docs/api/uagents/experimental/quota/__init__.md
- python/src/uagents/experimental/quota/__init__.py
Update experimental quota protocol to allow building from specification and role.
> fix(experimental): update quota protocol to allow protocol spec

- python/uagents-core/pyproject.toml
> chore(core): bump version from 0.3.7 to 0.3.8

- python/src/uagents/mailbox.py
Fixes uncaught exceptions when checking mailbox.
> fix(uagents): catch all exceptions when checking mailbox

- python/poetry.lock
- python/pyproject.toml
> chore(uagents): bump version to 0.22.9 for release

- python/tests/examples/40-external-agent/main.py
- python/uagents-core/uagents_core/contrib/protocols/chat/__init__.py
- python/uagents-core/uagents_core/types.py
- python/uagents-core/uagents_core/utils/messages.py
- Update message parsing utils
- Make prefix optional in agent_info
- Add Fast-api plus uagent-core integration example
> chore(core): minor utils updates and external agent example

- python/uagents-adapter/pyproject.toml
> chore(core): bump version uagents-adapter to 0.6.0

- python/uagents-adapter/README.md
- python/uagents-adapter/src/uagents_adapter/a2a_inbound/README.md
- python/uagents-adapter/src/uagents_adapter/a2a_outbound/readme.md
> fix(integration): Updating the adapter readmes
