fetchai/uAgents

- src/uagents/agent.py
- src/uagents/protocol.py
- tests/test_agent.py
- tests/test_protocol.py
Previously, interval tasks were being created on protocol inclusion, but now these are added along with the other background tasks, after the startup handlers are executed.
> refactor: ensure startup tasks occur before interval tasks

- src/uagents/agent.py
- src/uagents/config.py
When creating a bureau of agents that should be reachable externally and are not using the mailbox, users should set the endpoint of the bureau and need not set endpoints for the agents. Example:
```python
from uagents import Agent, Bureau
agent = Agent(name="agent")
port = 8000
bureau = Bureau(endpoint=f"http://127.0.0.1:{port}/submit", port=port)
bureau.add(agent)
bureau.run()
```
> feat: bureau overwrites agent endpoints

- .github/workflows/ci-tests.yml
- poetry.lock
- pyproject.toml
- tests/test_server.py
Updating to CosmPy 0.8.0 allows uAgents to support Python 3.11.
Also fixes a few linting errors.
> feat: support python 3.11

- src/uagents/agent.py
- src/uagents/asgi.py
- src/uagents/context.py
- src/uagents/dispatch.py
- src/uagents/mailbox.py
Use session ID of incoming messages whenever sending from a message handler.
Adds session to context so it will be available in message handlers, too.
> feat: use session id correctly

- src/uagents/asgi.py
- src/uagents/context.py
- src/uagents/query.py
- tests/test_server.py
Adds a `send_raw` function to send Json-encoded messages along with a schema digest for when the Pydantic Model is not available. This small refactor should be completely backwards compatible.
> feat: add context.send_raw function

- python/src/uagents/network.py
Permissions query changes in new version of name service contract.
CI tests should fail until contract is migrated.
> feat: update permissions query for name service contract

- python/src/uagents/context.py
Session ID should only be created when sending an envelope either:
- supplied to the new context on receiving an incoming envelope
- or generated when no context is already present
> fix: add new session id to envelope if not already present in context

- python/src/uagents/asgi.py
Uses the `CaseInsensitiveDict` from `requests.structures`.
> fix: make http headers case insensitive

- python/src/uagents/asgi.py
- python/tests/test_server.py
- Fixes issue where connecting from browser results in an uncaught 500 error
- Returns status OK when connecting from browser
- More informative error messages
> fix: improve request header parsing

- python/src/uagents/agent.py
- python/tests/test_agent.py
- Renames misnamed `_handle_error` function to `_send_error_message`
- Adds a default error handler that can easily be overwritten if desired
A possible bonus is that rather than an empty protocol being default, the default protocol will now have something in it.
> feat: add default error handler

- README.md
The main branch's examples link did not include the parent '/python' folder. I have replaced it with the correct '../python/examples' URL.
> docs: fixed broken examples link

- python/pyproject.toml
- python/src/uagents/wallet_messaging.py
This reverts an incorrect deletion of an import that appears to be unused but is actually important for agents that use the wallet messaging feature.
> chore: import wallet message and bump version for patch release

- python/src/uagents/wallet_messaging.py
Not all exceptions were being caught, leading to silent failure of the wallet messaging client.
> fix: catch all wallet messaging exceptions

- python/examples/13-agent-name-service/agent1.py
- python/examples/13-agent-name-service/agent2.py
- python/src/uagents/config.py
- python/src/uagents/network.py
- python/src/uagents/resolver.py
This PR performs the needed updates to match `ANAME v2.0` contract with uAgents.
Now funds are required to register a domain, by default we set the registration time= 24 hours.
There are 2 main scenarios when attempting to register a domain:
- If the domain is available it will be registered and update the record with the agent address
- If the domain is not available (already registered and active) but the current wallet is the owner of the domain it will only update the record with the agent address
- If the domain is not available and the current wallet is not the owner of the domain, no registration will be attempted since another wallet owns the domain
For the name registration example (examples/13-agent-name-service) domain `example.agent` has been registered for around 3 months for …
> feat: updates to match aname contract-V2

- python/examples/14-broadcast/main.py
- python/src/uagents/context.py
> chore: rename broadcast method

- python/src/uagents/experimental/dialogues/__init__.py
The agent will be able to pick up existing sessions from storage that are still valid.
This enables you to restart an agent within an active dialogue and continue as before.
> feat(core): add persistent dialogue sessions

- python/examples/14-broadcast/main.py
- python/src/uagents/communication.py
- python/src/uagents/context.py
- python/src/uagents/experimental/dialogues/__init__.py
- python/tests/test_context.py
Also the following:
- add optional session id to MsgStatus
- fix broadcast method due to changed API
- refactor error messages in send_exchange_envelope method
It is now possible to use a protocol digest for the destination argument in `Dialogue.start_dialogue(...)` to start a dialogue with multiple agents at the same time.
> feat(core): add broadcast functionality to dialogues

- python/src/uagents/communication.py
- python/src/uagents/dispatch.py
Restores the functionality of getting a return envelope when sending a sync message from a standalone function, as in https://github.com/fetchai/uAgents/blob/main/python/examples/08-local-network-interaction/sync_sender.py.
> fix(core): return envelope if no sinks in dispatcher

- python/pyproject.toml
Bump version to 0.13.1 to support the most recent fetchai-babble package.
> chore(core): bump version to 0.13.1

- python/src/uagents/agent.py
Add support for shutdown tasks within the agent Bureau
Closes #90 
To verify please execute the following snippet:
```python
from uagents import Agent, Bureau, Context
alice = Agent(name="Alice", seed="<seed>")
bob = Agent(name="Bob", seed="<seed>")
bureau = Bureau(
agents=[alice, bob],
port=8080,
endpoint="http://localhost:8080/submit",
)
@alice.on_event("startup")
async def startup1(ctx: Context):
ctx.logger.info(">>> Alice is starting up.")
@bob.on_event("startup")
async def startup2(ctx: Context):
ctx.logger.info(">>> Bob is starting up.")
@alice.on_event("shutdown")
async def shutdown1(ctx: Context):
ctx.logger.info(">>> Alice is shutting down.")
@bob.on_event("shutdown")
async def shutdown2(ctx: Context):
ctx.logger.info(">>> Bob is shutting down.")
bureau.run()
```
> feat(core): add bureau shutdown event support

- python/src/uagents/asgi.py
- python/src/uagents/crypto/__init__.py
- python/src/uagents/envelope.py
- python/src/uagents/mailbox.py
- python/src/uagents/registration.py
Refactor the Envelope verification code to always throw an exception if something is wrong or the signature is missing.
Closes: #459 
> refactor(core): all errors in signature verification now throw an exception

- python/examples/07-msg-verification/main.py
- python/src/uagents/agent.py
If an agent does not have an endpoint configured it should not register on the Almanac.
> fix(core): agent registration if no endpoint is provided

- python/src/uagents/agent.py
- python/src/uagents/context.py
- python/src/uagents/resolver.py
- Use `dateutil.parser` to allow datetimes with `Z` suffix, which breaks some older Python implementations of `datetime.fromisofromat()`.
- Build Almanac API url from agentverse config
> fix(core): python version-safe datetime parsing and almanac api url refactor

- python/examples/18-async-loops/external_loop_attach.py
- python/examples/18-async-loops/external_loop_run.py
- python/src/uagents/agent.py
- python/src/uagents/mailbox.py
Add better support for adding agent tasks to be awaited by an external event loop using `await agent.run_async()`.
https://github.com/fetchai/uAgents/issues/475
> feat(core): separate asyncio tasks and running

- python/src/uagents/network.py
This PR add a function to `NameServiceContract` to unregister domain name:
`name_service_contract.unregister(name, DOMAIN, my_wallet)`
> feat(core): add function to unregister domain name

- python/src/uagents/communication.py
Fixes synchronous responses, which were failing due to the new exception raised when envelope verification fails. Since all we want to know if whether the envelope is signed or not, we can replace the `if not env.verify()` check with `if env.signature is None`.
Fixes https://github.com/fetchai/uAgents/issues/502
> fix(core): check for env signature instead of trying to verify

- python/src/uagents/asgi.py
A new bug was introduced in the last PR where you'll receive an error log message from the ASGI server due to an incomplete message.
`ERROR:    ASGI callable returned without completing response.`
These logs would be triggered whenever a message has been sent as the callee would send an incomplete acknowledgement.
> fix(core): asgi error message due to missing body

- integrations/CONTRIBUTING.md
- integrations/finbert/src/agents/finbert_agent.py
- integrations/hackathons/career-craft/src/agents/resume creation/agent.py
- integrations/seo-agent/wrapper.py
- python/docs/installation.md
- python/scripts/do_release.py
> chore(core): fix some comments

- python/examples/08-local-network-interaction/agent1.py
- python/src/uagents/agent.py
Log link to agent inspector. Setting level to debug until production inspector is released.
> feat(core): log inspector link on startup

- python/src/uagents/registration.py
- python/src/uagents/types.py
- python/tests/test_registration.py
> feat(core): add metadata to agent attestation and remove location

- python/docs/api/uagents/agent.md
- python/docs/api/uagents/types.md
- python/src/uagents/agent.py
- python/src/uagents/envelope.py
- python/src/uagents/registration.py
- python/src/uagents/types.py
- python/tests/test_registration.py
Add metadata property to agent constructor.
The initial version will support metadata in the following form:
```python
class AgentGeolocation(BaseModel):
latitude: float
longitude: float
radius: int
class AgentMetadata(BaseModel):
geolocation: AgentGeolocation
```
Other metadata will be ignored which means the following agent will produce the respective output:
```python
agent = Agent(
metadata={
"geolocation": {
"latitude": 52.507410,
"longitude": 13.378240,
"radius": 50,
},
"mobility": True,
"useless_information": "This is a test",
},
)
print(agent.metadata)
>>> {'geolocation': {'latitude': 52.50741, 'longitude': 13.37824, 'radius': 50}}
```
> feat(core): add agent metadata property

- python/src/uagents/agent.py
- python/src/uagents/registration.py
- python/tests/test_registration.py
Metadata used in the registration should be a dict of strings. This PR coerces the data to str before sending the request.
> chore(core): add function to coerce metadata

- python/.pre-commit-config.yaml
- python/docs/api/uagents/agent.md
- python/docs/api/uagents/registration.md
- python/poetry.lock
- python/pyproject.toml
- python/src/uagents/agent.py
This addresses an issue where you'll want to set the registration policy manually but were not able (or rather it was difficult) do so because of the missing agent information that you'll only get after initialising an agent.
It also fixes an issue with the `on_rest_post` decorator where the `Request` Model was erroneously set as Optional.
> feat(core): enable update registration policy after agent init

- python/src/uagents/agent.py
- python/src/uagents/experimental/quota/__init__.py
This Protocol class can be used to rate limit `on_message` message handlers.
The rate limiter uses the agents storage to keep track of the number of requests made by another agent within a given time window. If the number of requests exceeds a specified limit, the rate limiter will block further requests until the time window resets.
> Default: Not rate limited, but you can set a default during initialization.
Additionally, the protocol can be used to set access control rules for handlers allowing or blocking specific agents from accessing the handler. The default access control rule can be set to allow or block all agents.
Both rules can work together to provide a secure and rate-limited environment for message handlers.
Usage examples:
```python
from uagents.experimental.quota import …
```
> feat(core): add experimental rate limiter agent and protocol

- python/src/uagents/experimental/quota/__init__.py
Fix functionality of the QuotaProtocol and add default AccessControl to enable protocol wide rules.
> fix(experimental): quota protocol fix

- python/docs/api/uagents/agent.md
- python/docs/api/uagents/crypto/__init__.md
- python/docs/api/uagents/experimental/quota/__init__.md
- python/docs/api/uagents/network.md
- python/docs/api/uagents/registration.md
- python/src/uagents/agent.py
cont. fixing the shutdown routines.
The last PR didn't properly address the `Bureau` so this PR aims to fix it.
> fix(core): bureau shutdown routine

- python/docs/api/uagents/agent.md
- python/docs/api/uagents/config.md
- python/docs/api/uagents/mailbox.md
- python/examples/11-mailbox-agents/alice.py
- python/examples/11-mailbox-agents/bob.py
- python/examples/12-remote-agents/agent1.py
- python/examples/17-stateful-communication/agent1.py
- python/examples/17-stateful-communication/agent2.py
- python/examples/17-stateful-communication/agent3.py
- python/examples/17-stateful-communication/agent4.py
- python/src/uagents/agent.py
- python/src/uagents/asgi.py
- python/src/uagents/config.py
- python/src/uagents/mailbox.py
- python/tests/test_config.py
- Add updates for new mailbox connection workflow
- Add support for proxy and custom agent registration
- Remove websocket connection, which hasn't been supported for a long time anyway
- Delete mailbox messages immediately after handling them instead of processing them in a queue
- Handle CORS preflight request
> feat(core): updates to mailbox and agentverse registration process

- python/docs/api/uagents/agent.md
- python/docs/api/uagents/mailbox.md
- python/examples/11-mailbox-agents/alice.py
- python/examples/11-mailbox-agents/bob.py
- python/src/uagents/agent.py
- python/src/uagents/config.py
- python/src/uagents/mailbox.py
Optionally publish agent details (name, readme, avatar url) after connecting with the local inspector.
> feat(core): publish agent details on connect

- python/src/uagents/agent.py
- python/src/uagents/asgi.py
- python/src/uagents/mailbox.py
Endpoint needs to be supplied to `/prove` endpoint for proxy agent.
> fix(core): proxy endpoint flow

- python/examples/04-storage/main.py
- python/src/uagents/agent.py
- python/src/uagents/network.py
- python/src/uagents/registration.py
- python/src/uagents/types.py
- python/tests/test_registration.py
In order to for the Almanac API to know whether an agent is registered on testnet or mainnet, it need to have access to the full prefixed agent identifier (`test-agent://agent1...`, `agent://agent1...`), not just the agent address.
https://github.com/fetchai/uAgents/issues/520
> chore(core): use agent identifier in almanac attestation

- python/src/uagents/mailbox.py
Make `prefix` attribute optional so that mailbox API will be backwards compatible with older/current uagents version
> feat(core): make agent address prefix optional in mailbox RegistrationRequest

- python/docs/api/uagents/mailbox.md
- python/docs/api/uagents/registration.md
- python/src/uagents/agent.py
- python/src/uagents/mailbox.py
- python/src/uagents/network.py
- python/src/uagents/registration.py
- python/src/uagents/types.py
Changing the field `address` to `identifier` in `AgentInfo` breaks the local agent inspector, so since this is not actually needed for the updated almanac attestation, let's simply add prefix as a new field to the `AgentInfo` model instead.
> refactor(core): separate prefix from address in agent info

- python/src/uagents/asgi.py
- python/tests/test_rest.py
This PR makes all agent REST endpoints available to any caller, except those used for the inspector which will still be restricted to localhost only.
> feat(core): allow general access to rest endpoints, except inspector ones

- python/src/uagents/agent.py
- python/src/uagents/network.py
- python/src/uagents/registration.py
- python/src/uagents/utils.py
Specifying a log_level on agent initialization will apply this log level to all loggers.
Started moving exception details to the DEBUG level for a cleaner "normal" output.
#601 
Refactorings. (No application logic touched)
> chore(core): improve logging control and experience

- python/docs/api/uagents/agent.md
- python/docs/api/uagents/network.md
- python/docs/api/uagents/resolver.md
- python/docs/api/uagents/utils.md
- python/examples/13-agent-name-service/agent1.py
- python/src/uagents/agent.py
- python/src/uagents/network.py
- python/src/uagents/resolver.py
- python/src/uagents/types.py
Improve interface for setting network between testnet and mainnet and add prefix attribute.
> chore(core): update network and prefix properties

- python/src/uagents/network.py
- python/src/uagents/resolver.py
Fix failing domain query tests.
> test(core): fix agent registration test

- python/src/uagents/agent.py
Including the internal protocol on agent initialization ensures that it will be set in `agent.info` when the agent is added to a BatchRegistrationPolicy. Previously, it was included on `agent.setup()` which only gets executed after the RegistrationPolicy has been prepared, thus bureau agents have never included their internal protocol in registration until now (leading to errors in the Almanac API in certain cases).
> fix(core): include internal protocol on agent init

- .github/workflows/ci-tests.yml
- .github/workflows/coverage.yml
- .gitignore
- DEVELOPING.md
- README.md
- python/docs/api/uagents/agent.md
- python/docs/api/uagents/context.md
- python/docs/api/uagents/models.md
- python/poetry.lock
- python/pyproject.toml
This PR adds Python3.13 compatibility and code coverage checks for our CI tests to increase overall code quality.
closes: #495
> feat(core): add python3.13 compatibility and code coverage checks

- python/src/uagents/context.py
- python/tests/test_context.py
Fixes a bug where leaving replies blank for an incoming message while defining replies in another handler results in valid replies being wrongly deemed invalid.
> fix(core): is_valid_reply should return True by default

- python/docs/api/uagents/context.md
- python/src/uagents/context.py
- python/tests/test_context.py
This feature will allow users to set multiple response types in the `send_and_receive()` method.
closes: #668
> feat(core): send_and_receive allow multiple response types

- python/uagents-core/uagents_core/utils/messages.py
Fixes a bug in the `send_message_to_agent()` method in `uagents_core.utils.messages` where if an exception was raised a variable was accessed that has not been assigned at that point.
```python
Failed to send message to agent: cannot access local variable 'response' where it is not associated with a value
```
> fix(core): response not assigned error

- python/docs/api/uagents/context.md
- python/src/uagents/agent.py
- python/src/uagents/context.py
- python/tests/test_context.py
Fixes erroneous logging errors on reply validation:
- Changes outbound message to a list in case multiple messages are sent to the same agent
- When replies are defined as empty, do not validate replies
> fix(core): reply validation

- python/src/uagents/network.py
- python/src/uagents/registration.py
- python/tests/test_flakey_network_registration.py
Check if wallet address has clearing registrar role when querying the registration fee. If so, it should send `funds=None` with the registration transaction.
> feat(core): check for contract role when getting registration fee

- python/docs/api/uagents/network.md
- python/docs/api/uagents/registration.md
- python/src/uagents/experimental/dialogues/__init__.py
- python/src/uagents/network.py
- python/src/uagents/registration.py
- python/tests/test_flakey_network_registration.py
Return registration transaction status and log hash on error. Also exposes tirneout height and gas limit parameters.
> chore(core): return registration tx response

- python/docs/api/uagents/registration.md
- python/src/uagents/registration.py
- python/tests/test_registration.py
- python/uagents-core/uagents_core/registration.py
- python/uagents-core/uagents_core/utils/registration.py
Flockx business agents want to send list type registration metadata via the fetchai SDK (that uses uagents-core), that's why I changed the type annotation.
> chore(core): change type annotation so that agent category list is "allowed" to be sent via register_in_almanac

- .gitignore
- python/uagents-core/uagents_core/registration.py
- python/uagents-core/uagents_core/utils/registration.py
Adds a `register_batch_in_almanac` function to registration utils, which utilizes the Almanac's [batch registration endpoint](https://github.com/fetchai/api-clients/blob/main/agentverse-client/agentverse_client/almanac/docs/AgentRegistrationAttestationBatch.md)
N/A
Because the `register_batch_in_almanac` function does not have unit tests or public-facing documentation, I didn't add any for this new function either. ~What is the recommended way to manually perform end-to-end tests for a new function like this?~ Changes were tested manually in a Python REPL.
> feat(core): Add register_batch_in_almanac function

- README.md
Replaced the outdated and broken link to the Fetch.ai agents concepts documentation in the README with the current valid URL (https://fetch.ai/docs/concepts). The new link provides up-to-date information about agents, their architecture, and usage within the Fetch.ai ecosystem.
> Update broken Fetch.ai agents documentation link

- python/uagents-core/uagents_core/contrib/protocols/chat/__init__.py
Provide constructors with default values for a more user-friendly interface for creating chat messages and content. We add constructors instead of adding defaults to the pydantic models to preserve the current protocol digest. On the next breaking update to the protocol, it might be better to add these as default values.
This will allow creating basic chat messages like:
```python
text_msg = ChatMessage([TextContent("Hello!")])
res_id =uuid4()
resource_msg = ChatMessage(
[
ResourceContent(
res_id,
Resource(uri=f"agent-storage://agentverse.ai/{res_id}"),
),
EndSessionContent(),
]
)
```
> feat(core): add constructors with default values to chat messages

- python/uagents-core/pyproject.toml
- python/uagents-core/uagents_core/utils/messages.py
- python/uagents-core/uagents_core/utils/resolver.py
Add support for sync messaging in uagents_core
> feat(core): support sync messaging in uagents-core

- .github/CODEOWNERS
- python/src/uagents/resolver.py
Use the agent prefix to determine which contract should be queried for agent domains (testnet or mainnet). If no prefix is provided, prefer mainnet if both exist.
> feat(core): better handling of agent prefix in domain resolution

- python/docs/api/uagents/mailbox.md
- python/src/uagents/mailbox.py
Before an agent's mailbox is setup, it will try to check messages and receive a 404 error from the server. Instead of logging this as an error, inform the user where to create a mailbox and only log this once.
> chore(uagents): set missing mailbox log level to warning and only log once
